### ISSUE TITLE
Problem with Instagram Insights

### ISSUE THREAD

**Issue by pmonuth-bt** [Gladior-B-V/instagram-insights-connector#1]
Hello  @daannijkamp

We're having an issue with the Instagram Insights Connector.
We already linked an account and now it says I should reconnect. Unfortunately that does not work.

Here are the screenshots.

Warm greetings
Patrick

<img width="624" alt="Bildschirmfoto 2022-05-04 um 10 27 53" src="https://user-images.githubusercontent.com/39886875/166647033-33ec12b5-06ab-48e8-95d7-3b78a4a8c67f.png">
<img width="936" alt="Bildschirmfoto 2022-05-04 um 10 27 11" src="https://user-images.githubusercontent.com/39886875/166647040-75e53046-2b30-4e5a-8704-06df21471246.png">

**Comment by zoedufrenne** [comment]
Hi Patrick,

Thanks for your message.
That doesn't look right. Was this a new connection or did you already had this dashboard (before 26 april)? 
Is it possible to revoke the access of this connector and make a new connection? 

I would like to hear from you, so I can help you!

**Comment by pmonuth-bt** [comment]
Hy Zoe,

Thank you for your answer.

Yes the interface was online before April 26th.
I would have deleted the registration data from Goolge Data studio and wanted to re-enter them and the same error comes up again.

Could you help me again or give me a tip?

**Comment by zoedufrenne** [comment]
Hi Patrick,

I will contact development and we will check the error.
I keep you updated.

**Comment by zoedufrenne** [comment]
Hi Patrick,

We've made some new changes. 
I hope this resolves your issue as well. Could you maybe try again and let me know if it's been succesfull? 

If not then please explain which steps you've followed so we can maybe recreate the issue.

**Comment by pmonuth-bt** [comment]
Hello Zoe, 

I tested it again and unfortunately it still doesn't work.

I even tried it with another Google account from us and it writes the error message as shown in the screencast.

I now make all connections via your data hub, that should work best, right?

Do you have any other ideas?

Attached is my screencast where you can see exactly what I'm doing :) [Link](https://cloud-dev.pcm-group.at/index.php/s/dkd4w7AqamwrY5a)

**Comment by zoedufrenne** [comment]
Hi Patrick,
Thanks for showing us the video. 
In the video I see twice the same error (Once in the data hub & the other time in data studio).

_"Error validating access token: The session has been invalidated because the user changed their password or Facebook has changed the session for security reasons."_

We show this message because we can't access the data. I can see in your video that the three connectors are still as an app validated in your account, but there is something changed why we can't access the data.

Could you revoke acces of the Instagram connector (That's the Gladior Connector app in Facebook)?
If you've done that, try and make a new credential in the Data Hub. 

Can you let us know if it worked?
